### ISSUE TITLE
onChangeIndex() doesn't always fire when using swipe feature

### ISSUE THREAD

**Issue by curtismenmuir** [gusgard/react-native-swiper-flatlist#110]
## Description
- When user manually swipes item to side numerous times, `onChangeIndex` callback occasionally is not fired. 
- I have stripped back the props I was passing to `<SwiperFlatList>` to the bare minimum (see code example below) and issue still seen.
- Issue only seen with manual swipe

## Info
- Issue seen on Android + iOS
- RN Version: `0.63.4` (also seen in `v0.62.2`)
- `react-native-swiper-flatlist` version: `3.0.14` (also seen in `v3.0.8`)

## Code Example: 
```
const LIST_ITEMS = [
  { title: 'Title 1 },
  { title: 'Title 2' },
  { title: 'Title 3' },
  { title: 'Title 4' },
];

export default class SwipeView extends Component {
  constructor(props) {
      super(props);
    }

  onChangeIndex({ index, prevIndex }) {
      console.log('New Index: ' + index);
    }
  
  renderItem = ({ item }) => {
      return <SwipeListItem item={item} />;
    };
  
  render() {
    return (
      <SwiperFlatList
        autoplay={false}
        data={LIST_ITEMS}
        renderItem={this.renderItem}
        showPagination={false}
        onChangeIndex={this.onChangeIndex.bind(this)}
      />
    )
  }
}
```

## Steps to recreate
- Render list with 4 items
- Swipe forward to index 1
- Swipe back to index 0
- Repeat swiping between index 0 & 1 many times
- onChangeIndex callback not always fired

**Comment by curtismenmuir** [comment]
I have found a work-around by also implementing `onMomentumScrollEnd` callback. Leaving this issue open incase you want to track the `onChangeIndex` issue.

**Comment by curtismenmuir** [comment]
Done a bit of digging into `onChangeIndex` issue and it looks like `_onChangeIndex()` in `SwiperFlatList.tsx` (line 77) receives the same value for `_index` and `_prevIndex` and this causes the `onChangeIndex` callback not to fire.

From a quick look, it seems like `_onViewableItemsChanged()` (line 181) is not setting the index on the swipe previous to the swipe which does not fire `onChangeIndex` callback. EG:
```
if (newItem.isViewable) {
  setCurrentIndexes((prevState) => ({ ...prevState, index: nextIndex }));
}
```
I will do some more digging when I have some free time.

**Comment by gusgard** [comment]
@curtismenmuir thanks for reporting the issue and the work-around, if you could take a deep look at it, it would be great 🙌

**Comment by gusgard** [comment]
@curtismenmuir thanks for reporting the issue and the work-around, if you could take a deep look at it, it would be great 🙌

**Comment by PaperMonster** [comment]
I also faced this issue. I noticed `paginationIndex` props of `PaginationComponent` always gives correct index. I found the value can be derived from parameters of `onViewableItemsChanged`. So here is my current workaround:
```javascript
 onViewableItemsChanged={(params) => console.log('index', params.changed?.[0]?.index)}
```

**Comment by arcsoftanil** [comment]
Same issue persist for me also. I have noticed that onchange index trigger after some delay. Any luck ?

**Comment by Priyadharshini-max** [comment]
I'm facing this issue , only when I swipe manually
![Screenshot_2022-06-03-12-43-05-61_4007cdf3d38763fe5bc19f163cbad3b9__01](https://user-images.githubusercontent.com/59358875/171806649-549c9a51-2570-4633-b35a-3ee129866117.jpg)
![Screenshot_2022-06-03-12-43-02-16_4007cdf3d38763fe5bc19f163cbad3b9__01](https://user-images.githubusercontent.com/59358875/171806756-ce298cd2-2387-4a10-aebe-37bc2b399719.jpg)

**Comment by Priyadharshini-max** [comment]
It show half image, I need to show like this when i swipe manuall
![Screenshot_2022-06-03-12-46-57-04_4007cdf3d38763fe5bc19f163cbad3b9__01](https://user-images.githubusercontent.com/59358875/171807003-f6d06376-3a00-4cda-bf2b-b1aad057c545.jpg)
y

**Comment by iortega-dev** [comment]
> Same issue persist for me also. I have noticed that onchange index trigger after some delay. Any luck ?

I'm facing the same delay issue... :(

**Comment by zachnicoll** [comment]
+1 experiencing this issue!

> I also faced this issue. I noticed `paginationIndex` props of `PaginationComponent` always gives correct index. I found the value can be derived from parameters of `onViewableItemsChanged`. So here is my current workaround:
> 
> ```js
>  onViewableItemsChanged={(params) => console.log('index', params.changed?.[0]?.index)}
> ```

^ This does not work for me.

**Comment by ShobanaBohs100** [comment]
+1 having the same issue when swipe manually.

@curtismenmuir can we refer you workaround anywhere? It will be really helpful.

**Comment by ShobanaBohs100** [comment]
figured out onMomentumScrollEnd solves the problem for now. Thanks @curtismenmuir 

Instead this,
`
	onChangeIndex={({ index }) => {
		setListIndex(index);
	}}
`	
we can use this prop to get the index
`
onMomentumScrollEnd={({ index }: any) => setListIndex(index)}
`

**Comment by varunkukade** [comment]
@ShobanaBohs100  onMomentumScrollEnd={({ index }: any) => setListIndex(index)} Thanks!!! this perfectly worked for IOS. but android still having same issue. What did you use for android?

**Comment by gusgard** [comment]
I did a few improvements (removing re-renders and adding support for `getItemLayout`), please use version `3.2.2` and let me know. Thanks

**Comment by bravecode** [comment]
@gusgard Still the same issue on 3.2.2 :(

**Comment by gusgard** [comment]
I wasn't able to reproduce it with Expo v48, is there an example or steps you can provide me ? @bravecode

**Comment by kishanvaghera** [comment]
i achieve this design and also created this code blog.
https://buzzstuck.com/react-native-swiper-component-implemented-with-flatlist/

**Comment by Riuhou** [comment]
/node_modules/react-native-swiper-flatlist/src/components/SwiperFlatList/SwiperFlatList.tsx      
     
```javascript
     const _onChangeIndex = React.useCallback(
       ({ index: _index, prevIndex: _prevIndex }: { index: number; prevIndex: number }) => {
       	
         // -> Moving it out of the condition can temporarily solve the issue. Another problem is that _onChangeIndex cannot be triggered immediately after the swipe, but needs to wait for a moment.
        onChangeIndex?.({ index: _index, prevIndex: _prevIndex });

         //  -> First swipe right, then swipe left will not trigger _onChangeIndex.
         if (_index !== _prevIndex) {
          onChangeIndex?.({ index: _index, prevIndex: _prevIndex });
         // onChangeIndex?.({ index: _index, prevIndex: _prevIndex });
         }
       },
       [onChangeIndex]
```

**Comment by iamsaadMehmood** [comment]
+1

**Comment by dprajapati1179** [comment]
If any one have any other work around for getting the index of current visible item then please let me know

**Comment by douglas-esportudo** [comment]
> I did a few improvements (removing re-renders and adding support for `getItemLayout`), please use version `3.2.2` and let me know. Thanks

This worked for me! I was having this issue with **onChangeIndex** function, it would reach the third item in the array and stop counting. I'm using the list vertically and have a fixed header at the top with a height of 90px. I believe in this part of the code
```
if (props.getItemLayout === undefined) {
      const itemDimension = vertical ? height : width;
      flatListProps.getItemLayout = (__data, ItemIndex: number) => ({
        length: itemDimension,
        offset: itemDimension * ItemIndex,
        index: ItemIndex,
      });
    }
```
the offset didn't match the height of the images in the list. I just needed to provide this information in the **SwiperFlatList**:

```
<SwiperFlatList
        data={content}
        renderItem={({index, item}) => renderItem({index, item})}
        vertical
        keyExtractor={item => item.itemId.toString()}
        getItemLayout={(_d, i) => ({
          length: Dimensions.get('window').height,
          index: i,
          offset: (Dimensions.get('window').height - 90) * i,
        })}
        onChangeIndex={({index, prevIndex}) => console.log(index)}
      />
```

Now the onChangeIndex function is correctly returning the visible index.
I'm not sure if it applies to everyone here, but it worked for my case.

**Comment by devakrishna33** [comment]
I can confirm that setting getItemLayout with correct dimensions triggers the onChangeIndex correctly, can it be added to the docs?

**Comment by lsps9150414** [comment]
hey @devakrishna33 could you kindly share your code snippet?

**Comment by phuocantd** [comment]
I using `viewabilityConfigCallbackPairs` change `onViewableItemsChanged`. It working for ios but not work with android :(((

**Comment by BLOCKMATERIAL** [comment]
same

**Comment by gusgard** [comment]
Should be fixed in `2.3.4`

**Comment by Qurat-ul-ainn** [comment]
> I also faced this issue. I noticed `paginationIndex` props of `PaginationComponent` always gives correct index. I found the value can be derived from parameters of `onViewableItemsChanged`. So here is my current workaround:
> 
> ```js
>  onViewableItemsChanged={(params) => console.log('index', params.changed?.[0]?.index)}
> ```

by using this getting an error "Changing onViewableChanged on the fly is not supported"
